import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DbStudy2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String url = "jdbc:mysql://localhost/?"
	            + "CharacterEncoding=UTF-8&" 
	            + "serverTimezone=UTC&"
	            + "allowPublicKeyRetrieval=true&" 
	            + "allowLoadLocalInfile=true&" 
	            + "allowMultiQueries=true";

	      String id = "root";
	      String pw = "1234";
	      
	      try {
			
	    	  Connection con = DriverManager.getConnection(url, id, pw);
	    	  
	    	  System.out.println("connecting succeed");
	    	  
	    	  
	    	  
	    	  Statement stmt = con.createStatement();
	    	  
	    	  stmt.executeUpdate("-- MySQL Script generated by MySQL Workbench\r\n"
	    	  		+ "-- Tue Nov 29 19:53:05 2022\r\n"
	    	  		+ "-- Model: New Model    Version: 1.0\r\n"
	    	  		+ "-- MySQL Workbench Forward Engineering\r\n"
	    	  		+ "\r\n"
	    	  		+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\r\n"
	    	  		+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\r\n"
	    	  		+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\r\n"
	    	  		+ "\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "-- Schema ex1\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "DROP SCHEMA IF EXISTS `ex2` ;\r\n"
	    	  		+ "\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "-- Schema ex1\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "CREATE SCHEMA IF NOT EXISTS `ex2` DEFAULT CHARACTER SET utf8 ;\r\n"
	    	  		+ "USE `ex2` ;\r\n"
	    	  		+ "\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "-- Table `ex1`.`table1`\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "CREATE TABLE IF NOT EXISTS `ex2`.`table1` (\r\n"
	    	  		+ "  `no` INT NOT NULL,\r\n"
	    	  		+ "  `name` VARCHAR(45) NULL,\r\n"
	    	  		+ "  `h` FLOAT NULL,\r\n"
	    	  		+ "  `w` INT NULL,\r\n"
	    	  		+ "  PRIMARY KEY (`no`))\r\n"
	    	  		+ "ENGINE = InnoDB;\r\n"
	    	  		+ "\r\n"
	    	  		+ "\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "-- Table `ex1`.`table2`\r\n"
	    	  		+ "-- -----------------------------------------------------\r\n"
	    	  		+ "CREATE TABLE IF NOT EXISTS `ex2`.`table2` (\r\n"
	    	  		+ "  `no` INT NOT NULL,\r\n"
	    	  		+ "  `name` VARCHAR(45) NULL,\r\n"
	    	  		+ "  `h` FLOAT NULL,\r\n"
	    	  		+ "  `w` INT NULL,\r\n"
	    	  		+ "  PRIMARY KEY (`no`))\r\n"
	    	  		+ "ENGINE = InnoDB;\r\n"
	    	  		+ "\r\n"
	    	  		+ "\r\n"
	    	  		+ "SET SQL_MODE=@OLD_SQL_MODE;\r\n"
	    	  		+ "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\r\n"
	    	  		+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\r\n"
	    	  		+ "");
	    	  stmt.executeUpdate("INSERT INTO `ex2`.`table1` (`no`, `name`, `h`, `w`) VALUES ('1', 'jj', '2', '30');\r\n"
	    	  		+ "");
	    	  
	    	  ResultSet rs = stmt.executeQuery("SELECT * FROM ex2.table1");
	    	  
	    	  while(rs.next()) {
	              for (int i = 1; i <= 4; i++) {
	                 System.out.print(rs.getObject(i) + " ");
	                 
	              }}

	    	  
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
